Import('qt_env')

env = qt_env.Clone()

env.AppendUnique(CPPDEFINES = [ 'GAMESKYRIM_LIBRARY' ])

env.RequiresGamebryo()

lib = env.SharedLibrary('gameSkyrim', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
